apiVersion: v1
kind: Secret
metadata:
  name: todo-api-secret
  namespace: todo-app
  labels:
    app: todo-api
    tier: backend
type: Opaque
stringData:
  DB_CONNECTION: "mongodb://appuser:apppass@mongodb:27017/test"
  DB_NAME: "test"
