apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: todo-app
  labels:
    app: mongodb
    tier: database
type: Opaque
stringData:
  MONGO_INITDB_ROOT_USERNAME: appuser
  MONGO_INITDB_ROOT_PASSWORD: apppass
  MONGO_INITDB_DATABASE: test
